// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum HostFormat: Int {
  case jpeg = 0
  case png = 1
  case webp = 2
  case heic = 3
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HostFormat(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HostFormat {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Run with:
/// flutter pub run pigeon \
///   --input pigeons/messages.dart
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ImageCompressPlusHostApi {
  func compressWithList(image: FlutterStandardTypedData, targetWidth: Int64, targetHeight: Int64, quality: Int64, rotate: Int64, autoCorrectionAngle: Bool, targetFormat: HostFormat, keepExif: Bool, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func compressWithFile(path: String, targetWidth: Int64, targetHeight: Int64, quality: Int64, rotate: Int64, autoCorrectionAngle: Bool, targetFormat: HostFormat, keepExif: Bool, numberOfRetries: Int64, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  func compressWithFileAndGetFile(path: String, targetWidth: Int64, targetHeight: Int64, quality: Int64, targetPath: String, rotate: Int64, autoCorrectionAngle: Bool, targetFormat: HostFormat, keepExif: Bool, numberOfRetries: Int64, completion: @escaping (Result<String?, Error>) -> Void)
  func showLog(value: Bool, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ImageCompressPlusHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ImageCompressPlusHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ImageCompressPlusHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let compressWithListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_compress_plus_ios.ImageCompressPlusHostApi.compressWithList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compressWithListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageArg = args[0] as! FlutterStandardTypedData
        let targetWidthArg = args[1] as! Int64
        let targetHeightArg = args[2] as! Int64
        let qualityArg = args[3] as! Int64
        let rotateArg = args[4] as! Int64
        let autoCorrectionAngleArg = args[5] as! Bool
        let targetFormatArg = args[6] as! HostFormat
        let keepExifArg = args[7] as! Bool
        api.compressWithList(image: imageArg, targetWidth: targetWidthArg, targetHeight: targetHeightArg, quality: qualityArg, rotate: rotateArg, autoCorrectionAngle: autoCorrectionAngleArg, targetFormat: targetFormatArg, keepExif: keepExifArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compressWithListChannel.setMessageHandler(nil)
    }
    let compressWithFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_compress_plus_ios.ImageCompressPlusHostApi.compressWithFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compressWithFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let targetWidthArg = args[1] as! Int64
        let targetHeightArg = args[2] as! Int64
        let qualityArg = args[3] as! Int64
        let rotateArg = args[4] as! Int64
        let autoCorrectionAngleArg = args[5] as! Bool
        let targetFormatArg = args[6] as! HostFormat
        let keepExifArg = args[7] as! Bool
        let numberOfRetriesArg = args[8] as! Int64
        api.compressWithFile(path: pathArg, targetWidth: targetWidthArg, targetHeight: targetHeightArg, quality: qualityArg, rotate: rotateArg, autoCorrectionAngle: autoCorrectionAngleArg, targetFormat: targetFormatArg, keepExif: keepExifArg, numberOfRetries: numberOfRetriesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compressWithFileChannel.setMessageHandler(nil)
    }
    let compressWithFileAndGetFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_compress_plus_ios.ImageCompressPlusHostApi.compressWithFileAndGetFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compressWithFileAndGetFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let targetWidthArg = args[1] as! Int64
        let targetHeightArg = args[2] as! Int64
        let qualityArg = args[3] as! Int64
        let targetPathArg = args[4] as! String
        let rotateArg = args[5] as! Int64
        let autoCorrectionAngleArg = args[6] as! Bool
        let targetFormatArg = args[7] as! HostFormat
        let keepExifArg = args[8] as! Bool
        let numberOfRetriesArg = args[9] as! Int64
        api.compressWithFileAndGetFile(path: pathArg, targetWidth: targetWidthArg, targetHeight: targetHeightArg, quality: qualityArg, targetPath: targetPathArg, rotate: rotateArg, autoCorrectionAngle: autoCorrectionAngleArg, targetFormat: targetFormatArg, keepExif: keepExifArg, numberOfRetries: numberOfRetriesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compressWithFileAndGetFileChannel.setMessageHandler(nil)
    }
    let showLogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_compress_plus_ios.ImageCompressPlusHostApi.showLog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showLogChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        api.showLog(value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showLogChannel.setMessageHandler(nil)
    }
  }
}
