// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package world.nailao.image_compress_plus

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class HostFormat(val raw: Int) {
  JPEG(0),
  PNG(1),
  WEBP(2),
  HEIC(3);

  companion object {
    fun ofRaw(raw: Int): HostFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HostFormat.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HostFormat -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Run with:
 * flutter pub run pigeon \
 *   --input pigeons/messages.dart
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ImageCompressPlusHostApi {
  fun compressWithList(image: ByteArray, targetWidth: Long, targetHeight: Long, quality: Long, rotate: Long, autoCorrectionAngle: Boolean, targetFormat: HostFormat, keepExif: Boolean, callback: (Result<ByteArray>) -> Unit)
  fun compressWithFile(path: String, targetWidth: Long, targetHeight: Long, quality: Long, rotate: Long, autoCorrectionAngle: Boolean, targetFormat: HostFormat, keepExif: Boolean, numberOfRetries: Long, callback: (Result<ByteArray?>) -> Unit)
  fun compressWithFileAndGetFile(path: String, targetWidth: Long, targetHeight: Long, quality: Long, targetPath: String, rotate: Long, autoCorrectionAngle: Boolean, targetFormat: HostFormat, keepExif: Boolean, numberOfRetries: Long, callback: (Result<String?>) -> Unit)
  fun showLog(value: Boolean, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by ImageCompressPlusHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ImageCompressPlusHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ImageCompressPlusHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_compress_plus_android.ImageCompressPlusHostApi.compressWithList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imageArg = args[0] as ByteArray
            val targetWidthArg = args[1] as Long
            val targetHeightArg = args[2] as Long
            val qualityArg = args[3] as Long
            val rotateArg = args[4] as Long
            val autoCorrectionAngleArg = args[5] as Boolean
            val targetFormatArg = args[6] as HostFormat
            val keepExifArg = args[7] as Boolean
            api.compressWithList(imageArg, targetWidthArg, targetHeightArg, qualityArg, rotateArg, autoCorrectionAngleArg, targetFormatArg, keepExifArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_compress_plus_android.ImageCompressPlusHostApi.compressWithFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val targetWidthArg = args[1] as Long
            val targetHeightArg = args[2] as Long
            val qualityArg = args[3] as Long
            val rotateArg = args[4] as Long
            val autoCorrectionAngleArg = args[5] as Boolean
            val targetFormatArg = args[6] as HostFormat
            val keepExifArg = args[7] as Boolean
            val numberOfRetriesArg = args[8] as Long
            api.compressWithFile(pathArg, targetWidthArg, targetHeightArg, qualityArg, rotateArg, autoCorrectionAngleArg, targetFormatArg, keepExifArg, numberOfRetriesArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_compress_plus_android.ImageCompressPlusHostApi.compressWithFileAndGetFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val targetWidthArg = args[1] as Long
            val targetHeightArg = args[2] as Long
            val qualityArg = args[3] as Long
            val targetPathArg = args[4] as String
            val rotateArg = args[5] as Long
            val autoCorrectionAngleArg = args[6] as Boolean
            val targetFormatArg = args[7] as HostFormat
            val keepExifArg = args[8] as Boolean
            val numberOfRetriesArg = args[9] as Long
            api.compressWithFileAndGetFile(pathArg, targetWidthArg, targetHeightArg, qualityArg, targetPathArg, rotateArg, autoCorrectionAngleArg, targetFormatArg, keepExifArg, numberOfRetriesArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_compress_plus_android.ImageCompressPlusHostApi.showLog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Boolean
            api.showLog(valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
