name: image_compress_plus_platform_interface
description: The platform interface of image_compress_plus.
repository: https://github.com/WuTangNaiLao/image_compress_plus
version: 2.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  cross_file: ^0.3.5+2
